spring.application.name=msprodutcs

spring.datasource.url=jdbc:mysql://localhost:3306/msprodutcs
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.cloud.compatibility-verifier.enabled=false
